### ISSUE TITLE
Update???

### ISSUE THREAD

**Issue by JEijiandrei** [herbix/chunkLauncher#7]
Can u pls update the launcher and fix the log4j issue and add other features?

**Comment by herbix** [comment]
The launcher itself doesn't use log4j.
Did you want me to fix it in minecraft?

**Comment by JEijiandrei** [comment]
oh so the launcher uses the official api soooo its not vulnerable in the exploit anymore?

**Comment by JEijiandrei** [comment]
also is the project still active?

**Comment by herbix** [comment]
> oh so the launcher uses the official api soooo its not vulnerable in the exploit anymore?

Launcher itself is not vulnerable, it doesn't use log4j and it downloads Minecraft from official sources. But Minecraft (most likely a old version) is vulnerable because it uses log4j. That means when you join a server, others may be able to run any code in your compute by just sending some messages. I think newer version of Minecraft has fixed it. It's also safe to play single player mode.

> also is the project still active?

I won't add new features. But I'll always fix bugs.

**Comment by JEijiandrei** [comment]
ok
